
function createTeams(players, individualItems, groupEvents, numTeams, teamNames) {
    
    players.forEach(player => {
      player.allocations = 0;
      player.mappedTeam = "";
      player.includedRatings = [];
    });
  
    
    const individualItemArrays = createSortedArrays(players, individualItems);
  
    let teams = Array(numTeams).fill([]).map((_, index) => ({
        players: [],
        name: teamNames[index] || `Team ${index + 1}`, 
        team_strength: 0
      }));;
    const teamStrengths = Array(numTeams).fill(0);

    teams = allocatePlayers(individualItemArrays, teams, teamStrengths);

    console.log(teams);
 
    teams = addGroupEventRatings(teams, players, groupEvents);

    teams.sort((a, b) => teamStrengths[a.length - 1] - teamStrengths[b.length - 1]);

    if (players.some(player => player.allocations === 0)) {
      const groupEventArrays = createSortedArrays(players, groupEvents);
      allocatePlayers(groupEventArrays, teams, teamStrengths);
    }

    if (players.some(player => player.mappedTeam === "")) {
      throw new Error("Error: Some players were not allocated to any team.");
    }

    const finalResult = teams.map(team => ({
        players: team.players,
        name: team.name,
        team_strength: team.team_strength
      }));
  
    return finalResult;
  }


  function addGroupEventRatings(teams, players, groupEvents) {
    for (const team of teams) {
      let teamStrengthGroupEvents = 0;
      for (const playerName of team['players']) {
        const player = players.find(p => p.name === playerName);
        if (player) {
          for (const groupEvent of groupEvents) {
            teamStrengthGroupEvents += player[groupEvent] || 0; 
          }
        }
      }
  
      team.team_strength += teamStrengthGroupEvents;
    }
    return teams;
  }
  
  
  function createSortedArrays(players, items) {
    const itemArrays = {};
    const highestRatings = {}; 
  
    for (const item of items) {
      const filteredPlayers = players.filter(player => player[item] > 0);
      if (filteredPlayers.length > 0) {
        highestRatings[item] = Math.max(...filteredPlayers.map(player => player[item]));
        itemArrays[item] = filteredPlayers.sort((a, b) => {
          const ratingDiff = b[item] - a[item];
          return ratingDiff !== 0 ? ratingDiff : a.name.localeCompare(b.name);
        });
      } else {
        itemArrays[item] = filteredPlayers;
      }
    }
  
    return Object.fromEntries(
        Object.entries(itemArrays)
          .sort((a, b) => {
            const countDiff = a.filter(player => player[a[0]] === highestRatings[a[0]]).length -
            b.filter(player => player[b[0]] === highestRatings[b[0]]).length;
          return countDiff !== 0 ? countDiff : highestRatings[a[0]] - highestRatings[b[0]];
          })
      );
    
  }
  
 
  function allocatePlayers(itemArrays, teams, teamStrengths) {
    let teamIndex = 0;
    let playerIndex = 0;
  
    for (const itemArray in itemArrays) {
      for (const player of itemArrays[itemArray]) {
        
        if (!player.mappedTeam) {
          teams[teamIndex].players.push(player.name);
          teams[teamIndex].team_strength += player[itemArray];
          player.mappedTeam = teams[teamIndex].name; 
          playerIndex++;
  
          
          teamIndex = (teamIndex + 1) % teams.length;
        }
      }
    }
    return teams;
  }

 
  
  
  function handlePlayerAllocation(player, currentRating, team,teams ) {
    if (player.allocations === 0) {
      team['players'].push(player);
      team.team_strength += currentRating;
      player.allocations++;
      player.mappedTeam = team.name;
      player.includedRatings.push(currentRating);
    } else if (player.allocations === 1) {
        const existing_Team = teams.filter(x=> x.name==player.mappedTeam);
        existing_Team.team_strength += currentRating;
        player.includedRatings.push(currentRating);
    } else if (player.allocations >= 2) {
        const lowestRating = Math.min(...player.includedRatings);
        if (currentRating > lowestRating) {
          const indexToReplace = player.includedRatings.indexOf(lowestRating);
          player.includedRatings[indexToReplace] = currentRating;
          team.team_strength += currentRating - lowestRating; // Adjust team strength with new rating
        }
      }
    }
  
  const playersdetails = [
	{
		"name": "Bernard Calhoun",
		"Chess": 4,
		"Caroms": 5,
		"TT": 0,
		"Badminton": 1,
		"LS": 4,
		"Sackrace": 1,
		"Fouzball": 5,
		"Jenga": 0,
		"PenaltyKick": 5,
		"BallOut": 1,
		"darting": 4,
		"football": 4,
		"cricket": 4,
		"Soap Football": 2,
		"Dodg ball": 4,
		"Tug of war": 1
	},
	{
		"name": "Elvis Sparks",
		"Chess": 1,
		"Caroms": 1,
		"TT": 2,
		"Badminton": 4,
		"LS": 3,
		"Sackrace": 1,
		"Fouzball": 3,
		"Jenga": 4,
		"PenaltyKick": 2,
		"BallOut": 0,
		"darting": 0,
		"football": 5,
		"cricket": 1,
		"Soap Football": 1,
		"Dodg ball": 2,
		"Tug of war": 3
	},
	{
		"name": "Cleo Wooten",
		"Chess": 0,
		"Caroms": 1,
		"TT": 1,
		"Badminton": 5,
		"LS": 3,
		"Sackrace": 3,
		"Fouzball": 4,
		"Jenga": 2,
		"PenaltyKick": 4,
		"BallOut": 4,
		"darting": 1,
		"football": 2,
		"cricket": 0,
		"Soap Football": 1,
		"Dodg ball": 4,
		"Tug of war": 0
	},
	{
		"name": "Wade Duncan",
		"Chess": 1,
		"Caroms": 3,
		"TT": 3,
		"Badminton": 3,
		"LS": 5,
		"Sackrace": 2,
		"Fouzball": 2,
		"Jenga": 1,
		"PenaltyKick": 3,
		"BallOut": 3,
		"darting": 4,
		"football": 2,
		"cricket": 1,
		"Soap Football": 5,
		"Dodg ball": 5,
		"Tug of war": 4
	},
	{
		"name": "Channing Prince",
		"Chess": 2,
		"Caroms": 3,
		"TT": 4,
		"Badminton": 2,
		"LS": 5,
		"Sackrace": 2,
		"Fouzball": 0,
		"Jenga": 4,
		"PenaltyKick": 3,
		"BallOut": 4,
		"darting": 2,
		"football": 4,
		"cricket": 2,
		"Soap Football": 5,
		"Dodg ball": 4,
		"Tug of war": 3
	},
	{
		"name": "Naomi Davidson",
		"Chess": 2,
		"Caroms": 4,
		"TT": 0,
		"Badminton": 4,
		"LS": 3,
		"Sackrace": 2,
		"Fouzball": 4,
		"Jenga": 3,
		"PenaltyKick": 4,
		"BallOut": 3,
		"darting": 3,
		"football": 4,
		"cricket": 1,
		"Soap Football": 4,
		"Dodg ball": 1,
		"Tug of war": 2
	},
	{
		"name": "Brenden Newton",
		"Chess": 5,
		"Caroms": 4,
		"TT": 4,
		"Badminton": 5,
		"LS": 5,
		"Sackrace": 1,
		"Fouzball": 3,
		"Jenga": 1,
		"PenaltyKick": 2,
		"BallOut": 4,
		"darting": 2,
		"football": 1,
		"cricket": 2,
		"Soap Football": 5,
		"Dodg ball": 4,
		"Tug of war": 2
	},
	{
		"name": "Otto Peck",
		"Chess": 4,
		"Caroms": 0,
		"TT": 4,
		"Badminton": 5,
		"LS": 4,
		"Sackrace": 4,
		"Fouzball": 3,
		"Jenga": 0,
		"PenaltyKick": 0,
		"BallOut": 1,
		"darting": 0,
		"football": 5,
		"cricket": 3,
		"Soap Football": 1,
		"Dodg ball": 3,
		"Tug of war": 2
	},
	{
		"name": "Regina Mcdonald",
		"Chess": 1,
		"Caroms": 1,
		"TT": 1,
		"Badminton": 1,
		"LS": 3,
		"Sackrace": 0,
		"Fouzball": 4,
		"Jenga": 1,
		"PenaltyKick": 1,
		"BallOut": 5,
		"darting": 2,
		"football": 1,
		"cricket": 0,
		"Soap Football": 5,
		"Dodg ball": 1,
		"Tug of war": 3
	},
	{
		"name": "Nissim Schmidt",
		"Chess": 2,
		"Caroms": 2,
		"TT": 0,
		"Badminton": 1,
		"LS": 1,
		"Sackrace": 4,
		"Fouzball": 5,
		"Jenga": 3,
		"PenaltyKick": 1,
		"BallOut": 3,
		"darting": 2,
		"football": 0,
		"cricket": 3,
		"Soap Football": 2,
		"Dodg ball": 5,
		"Tug of war": 2
	},
	{
		"name": "Yasir Mueller",
		"Chess": 0,
		"Caroms": 1,
		"TT": 2,
		"Badminton": 1,
		"LS": 2,
		"Sackrace": 3,
		"Fouzball": 3,
		"Jenga": 4,
		"PenaltyKick": 1,
		"BallOut": 4,
		"darting": 2,
		"football": 1,
		"cricket": 4,
		"Soap Football": 2,
		"Dodg ball": 5,
		"Tug of war": 5
	},
	{
		"name": "Emery Montoya",
		"Chess": 3,
		"Caroms": 1,
		"TT": 1,
		"Badminton": 2,
		"LS": 2,
		"Sackrace": 4,
		"Fouzball": 1,
		"Jenga": 5,
		"PenaltyKick": 2,
		"BallOut": 5,
		"darting": 1,
		"football": 2,
		"cricket": 0,
		"Soap Football": 5,
		"Dodg ball": 5,
		"Tug of war": 3
	},
	{
		"name": "Orla Conley",
		"Chess": 4,
		"Caroms": 4,
		"TT": 4,
		"Badminton": 4,
		"LS": 0,
		"Sackrace": 5,
		"Fouzball": 0,
		"Jenga": 1,
		"PenaltyKick": 2,
		"BallOut": 0,
		"darting": 1,
		"football": 1,
		"cricket": 1,
		"Soap Football": 3,
		"Dodg ball": 2,
		"Tug of war": 2
	},
	{
		"name": "Blaze Morse",
		"Chess": 4,
		"Caroms": 2,
		"TT": 1,
		"Badminton": 1,
		"LS": 4,
		"Sackrace": 1,
		"Fouzball": 1,
		"Jenga": 5,
		"PenaltyKick": 5,
		"BallOut": 1,
		"darting": 1,
		"football": 2,
		"cricket": 1,
		"Soap Football": 2,
		"Dodg ball": 3,
		"Tug of war": 0
	},
	{
		"name": "Joan Hughes",
		"Chess": 3,
		"Caroms": 1,
		"TT": 4,
		"Badminton": 2,
		"LS": 5,
		"Sackrace": 3,
		"Fouzball": 1,
		"Jenga": 3,
		"PenaltyKick": 1,
		"BallOut": 1,
		"darting": 0,
		"football": 1,
		"cricket": 2,
		"Soap Football": 3,
		"Dodg ball": 1,
		"Tug of war": 0
	},
	{
		"name": "Basia Jennings",
		"Chess": 1,
		"Caroms": 2,
		"TT": 3,
		"Badminton": 3,
		"LS": 1,
		"Sackrace": 2,
		"Fouzball": 4,
		"Jenga": 3,
		"PenaltyKick": 3,
		"BallOut": 1,
		"darting": 0,
		"football": 3,
		"cricket": 4,
		"Soap Football": 0,
		"Dodg ball": 3,
		"Tug of war": 2
	},
	{
		"name": "Orson Murphy",
		"Chess": 5,
		"Caroms": 3,
		"TT": 1,
		"Badminton": 2,
		"LS": 3,
		"Sackrace": 1,
		"Fouzball": 5,
		"Jenga": 5,
		"PenaltyKick": 4,
		"BallOut": 4,
		"darting": 2,
		"football": 3,
		"cricket": 1,
		"Soap Football": 2,
		"Dodg ball": 4,
		"Tug of war": 0
	},
	{
		"name": "Latifah King",
		"Chess": 1,
		"Caroms": 4,
		"TT": 0,
		"Badminton": 2,
		"LS": 0,
		"Sackrace": 4,
		"Fouzball": 3,
		"Jenga": 3,
		"PenaltyKick": 2,
		"BallOut": 3,
		"darting": 2,
		"football": 3,
		"cricket": 3,
		"Soap Football": 3,
		"Dodg ball": 1,
		"Tug of war": 1
	},
	{
		"name": "Samuel Gamble",
		"Chess": 3,
		"Caroms": 2,
		"TT": 2,
		"Badminton": 1,
		"LS": 4,
		"Sackrace": 3,
		"Fouzball": 0,
		"Jenga": 1,
		"PenaltyKick": 0,
		"BallOut": 1,
		"darting": 3,
		"football": 3,
		"cricket": 4,
		"Soap Football": 2,
		"Dodg ball": 1,
		"Tug of war": 3
	},
	{
		"name": "Dara Hunter",
		"Chess": 0,
		"Caroms": 5,
		"TT": 4,
		"Badminton": 0,
		"LS": 2,
		"Sackrace": 4,
		"Fouzball": 4,
		"Jenga": 4,
		"PenaltyKick": 3,
		"BallOut": 5,
		"darting": 4,
		"football": 4,
		"cricket": 0,
		"Soap Football": 3,
		"Dodg ball": 4,
		"Tug of war": 4
	},
	{
		"name": "Garrett Owen",
		"Chess": 4,
		"Caroms": 0,
		"TT": 1,
		"Badminton": 3,
		"LS": 1,
		"Sackrace": 3,
		"Fouzball": 2,
		"Jenga": 0,
		"PenaltyKick": 0,
		"BallOut": 5,
		"darting": 1,
		"football": 2,
		"cricket": 3,
		"Soap Football": 0,
		"Dodg ball": 4,
		"Tug of war": 2
	},
	{
		"name": "Eugenia Nixon",
		"Chess": 3,
		"Caroms": 5,
		"TT": 4,
		"Badminton": 0,
		"LS": 2,
		"Sackrace": 0,
		"Fouzball": 2,
		"Jenga": 4,
		"PenaltyKick": 2,
		"BallOut": 0,
		"darting": 5,
		"football": 2,
		"cricket": 3,
		"Soap Football": 4,
		"Dodg ball": 1,
		"Tug of war": 0
	},
	{
		"name": "Heidi Park",
		"Chess": 5,
		"Caroms": 3,
		"TT": 0,
		"Badminton": 3,
		"LS": 5,
		"Sackrace": 3,
		"Fouzball": 3,
		"Jenga": 4,
		"PenaltyKick": 3,
		"BallOut": 0,
		"darting": 5,
		"football": 2,
		"cricket": 4,
		"Soap Football": 5,
		"Dodg ball": 3,
		"Tug of war": 1
	},
	{
		"name": "Ginger Sawyer",
		"Chess": 2,
		"Caroms": 1,
		"TT": 2,
		"Badminton": 4,
		"LS": 0,
		"Sackrace": 2,
		"Fouzball": 4,
		"Jenga": 4,
		"PenaltyKick": 1,
		"BallOut": 5,
		"darting": 2,
		"football": 4,
		"cricket": 1,
		"Soap Football": 2,
		"Dodg ball": 3,
		"Tug of war": 2
	},
	{
		"name": "Deborah Fischer",
		"Chess": 4,
		"Caroms": 3,
		"TT": 1,
		"Badminton": 4,
		"LS": 2,
		"Sackrace": 4,
		"Fouzball": 1,
		"Jenga": 3,
		"PenaltyKick": 2,
		"BallOut": 5,
		"darting": 1,
		"football": 3,
		"cricket": 4,
		"Soap Football": 1,
		"Dodg ball": 4,
		"Tug of war": 4
	},
	{
		"name": "Cade Coleman",
		"Chess": 1,
		"Caroms": 4,
		"TT": 4,
		"Badminton": 4,
		"LS": 1,
		"Sackrace": 1,
		"Fouzball": 1,
		"Jenga": 3,
		"PenaltyKick": 4,
		"BallOut": 3,
		"darting": 3,
		"football": 1,
		"cricket": 2,
		"Soap Football": 3,
		"Dodg ball": 3,
		"Tug of war": 1
	},
	{
		"name": "Barrett Hughes",
		"Chess": 2,
		"Caroms": 4,
		"TT": 2,
		"Badminton": 1,
		"LS": 3,
		"Sackrace": 0,
		"Fouzball": 2,
		"Jenga": 1,
		"PenaltyKick": 4,
		"BallOut": 4,
		"darting": 4,
		"football": 2,
		"cricket": 3,
		"Soap Football": 0,
		"Dodg ball": 2,
		"Tug of war": 3
	},
	{
		"name": "Brenda Branch",
		"Chess": 3,
		"Caroms": 5,
		"TT": 4,
		"Badminton": 2,
		"LS": 0,
		"Sackrace": 1,
		"Fouzball": 3,
		"Jenga": 3,
		"PenaltyKick": 4,
		"BallOut": 4,
		"darting": 4,
		"football": 3,
		"cricket": 2,
		"Soap Football": 1,
		"Dodg ball": 5,
		"Tug of war": 3
	},
	{
		"name": "Liberty Mccarty",
		"Chess": 1,
		"Caroms": 4,
		"TT": 2,
		"Badminton": 3,
		"LS": 4,
		"Sackrace": 3,
		"Fouzball": 3,
		"Jenga": 3,
		"PenaltyKick": 1,
		"BallOut": 4,
		"darting": 2,
		"football": 4,
		"cricket": 3,
		"Soap Football": 2,
		"Dodg ball": 3,
		"Tug of war": 1
	},
	{
		"name": "Samuel Mullins",
		"Chess": 4,
		"Caroms": 0,
		"TT": 5,
		"Badminton": 3,
		"LS": 4,
		"Sackrace": 5,
		"Fouzball": 4,
		"Jenga": 4,
		"PenaltyKick": 3,
		"BallOut": 2,
		"darting": 4,
		"football": 4,
		"cricket": 2,
		"Soap Football": 3,
		"Dodg ball": 3,
		"Tug of war": 4
	},
	{
		"name": "Hayfa Dillard",
		"Chess": 4,
		"Caroms": 2,
		"TT": 1,
		"Badminton": 1,
		"LS": 4,
		"Sackrace": 1,
		"Fouzball": 3,
		"Jenga": 0,
		"PenaltyKick": 5,
		"BallOut": 2,
		"darting": 2,
		"football": 5,
		"cricket": 3,
		"Soap Football": 0,
		"Dodg ball": 4,
		"Tug of war": 3
	},
	{
		"name": "Moses Schultz",
		"Chess": 2,
		"Caroms": 1,
		"TT": 2,
		"Badminton": 0,
		"LS": 3,
		"Sackrace": 5,
		"Fouzball": 5,
		"Jenga": 5,
		"PenaltyKick": 4,
		"BallOut": 2,
		"darting": 2,
		"football": 5,
		"cricket": 4,
		"Soap Football": 4,
		"Dodg ball": 4,
		"Tug of war": 4
	},
	{
		"name": "Howard Sawyer",
		"Chess": 2,
		"Caroms": 2,
		"TT": 1,
		"Badminton": 2,
		"LS": 0,
		"Sackrace": 5,
		"Fouzball": 3,
		"Jenga": 3,
		"PenaltyKick": 4,
		"BallOut": 3,
		"darting": 3,
		"football": 2,
		"cricket": 2,
		"Soap Football": 4,
		"Dodg ball": 3,
		"Tug of war": 5
	},
	{
		"name": "Moses Barnes",
		"Chess": 2,
		"Caroms": 1,
		"TT": 1,
		"Badminton": 4,
		"LS": 1,
		"Sackrace": 1,
		"Fouzball": 3,
		"Jenga": 1,
		"PenaltyKick": 1,
		"BallOut": 0,
		"darting": 0,
		"football": 1,
		"cricket": 0,
		"Soap Football": 2,
		"Dodg ball": 4,
		"Tug of war": 4
	},
	{
		"name": "Raymond Herrera",
		"Chess": 1,
		"Caroms": 4,
		"TT": 5,
		"Badminton": 4,
		"LS": 2,
		"Sackrace": 3,
		"Fouzball": 5,
		"Jenga": 1,
		"PenaltyKick": 3,
		"BallOut": 0,
		"darting": 4,
		"football": 4,
		"cricket": 1,
		"Soap Football": 4,
		"Dodg ball": 2,
		"Tug of war": 4
	},
	{
		"name": "Tashya Stafford",
		"Chess": 3,
		"Caroms": 0,
		"TT": 2,
		"Badminton": 3,
		"LS": 3,
		"Sackrace": 4,
		"Fouzball": 1,
		"Jenga": 4,
		"PenaltyKick": 3,
		"BallOut": 2,
		"darting": 4,
		"football": 1,
		"cricket": 2,
		"Soap Football": 2,
		"Dodg ball": 1,
		"Tug of war": 2
	},
	{
		"name": "Macaulay Gray",
		"Chess": 4,
		"Caroms": 1,
		"TT": 2,
		"Badminton": 4,
		"LS": 2,
		"Sackrace": 2,
		"Fouzball": 3,
		"Jenga": 1,
		"PenaltyKick": 2,
		"BallOut": 1,
		"darting": 1,
		"football": 3,
		"cricket": 0,
		"Soap Football": 2,
		"Dodg ball": 2,
		"Tug of war": 0
	},
	{
		"name": "Cyrus Parrish",
		"Chess": 3,
		"Caroms": 2,
		"TT": 0,
		"Badminton": 5,
		"LS": 2,
		"Sackrace": 3,
		"Fouzball": 3,
		"Jenga": 3,
		"PenaltyKick": 3,
		"BallOut": 1,
		"darting": 1,
		"football": 5,
		"cricket": 2,
		"Soap Football": 2,
		"Dodg ball": 3,
		"Tug of war": 3
	},
	{
		"name": "Whoopi Lane",
		"Chess": 1,
		"Caroms": 1,
		"TT": 0,
		"Badminton": 2,
		"LS": 1,
		"Sackrace": 2,
		"Fouzball": 4,
		"Jenga": 1,
		"PenaltyKick": 5,
		"BallOut": 1,
		"darting": 1,
		"football": 2,
		"cricket": 1,
		"Soap Football": 3,
		"Dodg ball": 4,
		"Tug of war": 4
	},
	{
		"name": "Aretha Wallace",
		"Chess": 2,
		"Caroms": 3,
		"TT": 2,
		"Badminton": 1,
		"LS": 1,
		"Sackrace": 4,
		"Fouzball": 0,
		"Jenga": 4,
		"PenaltyKick": 4,
		"BallOut": 3,
		"darting": 3,
		"football": 4,
		"cricket": 4,
		"Soap Football": 3,
		"Dodg ball": 5,
		"Tug of war": 3
	},
	{
		"name": "Zeus Vance",
		"Chess": 3,
		"Caroms": 1,
		"TT": 1,
		"Badminton": 2,
		"LS": 2,
		"Sackrace": 3,
		"Fouzball": 5,
		"Jenga": 4,
		"PenaltyKick": 1,
		"BallOut": 2,
		"darting": 2,
		"football": 3,
		"cricket": 4,
		"Soap Football": 0,
		"Dodg ball": 4,
		"Tug of war": 1
	},
	{
		"name": "Quinlan Johnston",
		"Chess": 4,
		"Caroms": 0,
		"TT": 1,
		"Badminton": 3,
		"LS": 0,
		"Sackrace": 3,
		"Fouzball": 0,
		"Jenga": 2,
		"PenaltyKick": 0,
		"BallOut": 0,
		"darting": 2,
		"football": 1,
		"cricket": 5,
		"Soap Football": 3,
		"Dodg ball": 2,
		"Tug of war": 3
	},
	{
		"name": "Julie Bailey",
		"Chess": 4,
		"Caroms": 1,
		"TT": 3,
		"Badminton": 0,
		"LS": 1,
		"Sackrace": 4,
		"Fouzball": 4,
		"Jenga": 0,
		"PenaltyKick": 2,
		"BallOut": 4,
		"darting": 1,
		"football": 1,
		"cricket": 1,
		"Soap Football": 4,
		"Dodg ball": 2,
		"Tug of war": 5
	},
	{
		"name": "Ivor Haley",
		"Chess": 4,
		"Caroms": 2,
		"TT": 2,
		"Badminton": 1,
		"LS": 4,
		"Sackrace": 1,
		"Fouzball": 4,
		"Jenga": 0,
		"PenaltyKick": 1,
		"BallOut": 1,
		"darting": 4,
		"football": 3,
		"cricket": 2,
		"Soap Football": 3,
		"Dodg ball": 4,
		"Tug of war": 1
	},
	{
		"name": "Marny Humphrey",
		"Chess": 4,
		"Caroms": 4,
		"TT": 2,
		"Badminton": 2,
		"LS": 5,
		"Sackrace": 4,
		"Fouzball": 3,
		"Jenga": 4,
		"PenaltyKick": 3,
		"BallOut": 1,
		"darting": 3,
		"football": 3,
		"cricket": 4,
		"Soap Football": 1,
		"Dodg ball": 2,
		"Tug of war": 3
	},
	{
		"name": "Barry Conner",
		"Chess": 0,
		"Caroms": 1,
		"TT": 2,
		"Badminton": 5,
		"LS": 3,
		"Sackrace": 3,
		"Fouzball": 4,
		"Jenga": 5,
		"PenaltyKick": 4,
		"BallOut": 5,
		"darting": 1,
		"football": 1,
		"cricket": 5,
		"Soap Football": 2,
		"Dodg ball": 3,
		"Tug of war": 4
	},
	{
		"name": "Gabriel Travis",
		"Chess": 3,
		"Caroms": 4,
		"TT": 1,
		"Badminton": 3,
		"LS": 4,
		"Sackrace": 4,
		"Fouzball": 1,
		"Jenga": 4,
		"PenaltyKick": 3,
		"BallOut": 4,
		"darting": 1,
		"football": 5,
		"cricket": 4,
		"Soap Football": 4,
		"Dodg ball": 3,
		"Tug of war": 4
	},
	{
		"name": "Anjolie Allison",
		"Chess": 0,
		"Caroms": 1,
		"TT": 1,
		"Badminton": 0,
		"LS": 5,
		"Sackrace": 3,
		"Fouzball": 4,
		"Jenga": 5,
		"PenaltyKick": 2,
		"BallOut": 0,
		"darting": 3,
		"football": 1,
		"cricket": 0,
		"Soap Football": 2,
		"Dodg ball": 3,
		"Tug of war": 3
	},
	{
		"name": "Oren Valentine",
		"Chess": 4,
		"Caroms": 5,
		"TT": 2,
		"Badminton": 2,
		"LS": 1,
		"Sackrace": 4,
		"Fouzball": 1,
		"Jenga": 3,
		"PenaltyKick": 3,
		"BallOut": 3,
		"darting": 3,
		"football": 4,
		"cricket": 4,
		"Soap Football": 1,
		"Dodg ball": 2,
		"Tug of war": 1
	},
	{
		"name": "Davis Curtis",
		"Chess": 4,
		"Caroms": 1,
		"TT": 2,
		"Badminton": 4,
		"LS": 1,
		"Sackrace": 3,
		"Fouzball": 4,
		"Jenga": 3,
		"PenaltyKick": 1,
		"BallOut": 0,
		"darting": 1,
		"football": 3,
		"cricket": 3,
		"Soap Football": 5,
		"Dodg ball": 2,
		"Tug of war": 2
	},
	{
		"name": "Grady Schmidt",
		"Chess": 2,
		"Caroms": 3,
		"TT": 3,
		"Badminton": 1,
		"LS": 3,
		"Sackrace": 5,
		"Fouzball": 4,
		"Jenga": 3,
		"PenaltyKick": 3,
		"BallOut": 2,
		"darting": 0,
		"football": 2,
		"cricket": 1,
		"Soap Football": 1,
		"Dodg ball": 3,
		"Tug of war": 2
	},
	{
		"name": "Brenda Hensley",
		"Chess": 1,
		"Caroms": 2,
		"TT": 3,
		"Badminton": 0,
		"LS": 1,
		"Sackrace": 2,
		"Fouzball": 4,
		"Jenga": 3,
		"PenaltyKick": 3,
		"BallOut": 4,
		"darting": 1,
		"football": 4,
		"cricket": 4,
		"Soap Football": 2,
		"Dodg ball": 2,
		"Tug of war": 2
	},
	{
		"name": "Kitra Massey",
		"Chess": 2,
		"Caroms": 3,
		"TT": 5,
		"Badminton": 1,
		"LS": 0,
		"Sackrace": 1,
		"Fouzball": 2,
		"Jenga": 3,
		"PenaltyKick": 1,
		"BallOut": 0,
		"darting": 2,
		"football": 2,
		"cricket": 2,
		"Soap Football": 3,
		"Dodg ball": 4,
		"Tug of war": 4
	},
	{
		"name": "Christine Griffin",
		"Chess": 2,
		"Caroms": 3,
		"TT": 3,
		"Badminton": 3,
		"LS": 2,
		"Sackrace": 2,
		"Fouzball": 0,
		"Jenga": 3,
		"PenaltyKick": 5,
		"BallOut": 4,
		"darting": 4,
		"football": 2,
		"cricket": 2,
		"Soap Football": 5,
		"Dodg ball": 0,
		"Tug of war": 1
	},
	{
		"name": "Devin Mccarthy",
		"Chess": 0,
		"Caroms": 2,
		"TT": 3,
		"Badminton": 3,
		"LS": 0,
		"Sackrace": 5,
		"Fouzball": 4,
		"Jenga": 5,
		"PenaltyKick": 3,
		"BallOut": 3,
		"darting": 2,
		"football": 0,
		"cricket": 5,
		"Soap Football": 3,
		"Dodg ball": 0,
		"Tug of war": 4
	},
	{
		"name": "Christian Hebert",
		"Chess": 1,
		"Caroms": 2,
		"TT": 3,
		"Badminton": 5,
		"LS": 3,
		"Sackrace": 5,
		"Fouzball": 1,
		"Jenga": 2,
		"PenaltyKick": 4,
		"BallOut": 1,
		"darting": 1,
		"football": 1,
		"cricket": 2,
		"Soap Football": 4,
		"Dodg ball": 2,
		"Tug of war": 0
	},
	{
		"name": "Barbara Christian",
		"Chess": 1,
		"Caroms": 2,
		"TT": 3,
		"Badminton": 5,
		"LS": 5,
		"Sackrace": 4,
		"Fouzball": 2,
		"Jenga": 1,
		"PenaltyKick": 3,
		"BallOut": 1,
		"darting": 4,
		"football": 3,
		"cricket": 2,
		"Soap Football": 4,
		"Dodg ball": 4,
		"Tug of war": 4
	},
	{
		"name": "Vielka Briggs",
		"Chess": 3,
		"Caroms": 1,
		"TT": 0,
		"Badminton": 4,
		"LS": 2,
		"Sackrace": 3,
		"Fouzball": 3,
		"Jenga": 1,
		"PenaltyKick": 5,
		"BallOut": 1,
		"darting": 0,
		"football": 2,
		"cricket": 1,
		"Soap Football": 1,
		"Dodg ball": 4,
		"Tug of war": 4
	},
	{
		"name": "Evan Alford",
		"Chess": 2,
		"Caroms": 0,
		"TT": 4,
		"Badminton": 2,
		"LS": 4,
		"Sackrace": 4,
		"Fouzball": 3,
		"Jenga": 0,
		"PenaltyKick": 4,
		"BallOut": 4,
		"darting": 3,
		"football": 2,
		"cricket": 2,
		"Soap Football": 1,
		"Dodg ball": 0,
		"Tug of war": 2
	},
	{
		"name": "Aristotle Stevenson",
		"Chess": 0,
		"Caroms": 2,
		"TT": 3,
		"Badminton": 4,
		"LS": 4,
		"Sackrace": 3,
		"Fouzball": 2,
		"Jenga": 1,
		"PenaltyKick": 4,
		"BallOut": 0,
		"darting": 4,
		"football": 1,
		"cricket": 2,
		"Soap Football": 4,
		"Dodg ball": 1,
		"Tug of war": 3
	},
	{
		"name": "Shannon York",
		"Chess": 1,
		"Caroms": 0,
		"TT": 1,
		"Badminton": 1,
		"LS": 4,
		"Sackrace": 4,
		"Fouzball": 2,
		"Jenga": 4,
		"PenaltyKick": 2,
		"BallOut": 1,
		"darting": 1,
		"football": 3,
		"cricket": 2,
		"Soap Football": 3,
		"Dodg ball": 2,
		"Tug of war": 3
	},
	{
		"name": "MacKensie Curtis",
		"Chess": 2,
		"Caroms": 1,
		"TT": 2,
		"Badminton": 3,
		"LS": 4,
		"Sackrace": 2,
		"Fouzball": 5,
		"Jenga": 3,
		"PenaltyKick": 4,
		"BallOut": 3,
		"darting": 1,
		"football": 1,
		"cricket": 5,
		"Soap Football": 5,
		"Dodg ball": 4,
		"Tug of war": 2
	},
	{
		"name": "Camille Mendoza",
		"Chess": 3,
		"Caroms": 1,
		"TT": 4,
		"Badminton": 0,
		"LS": 4,
		"Sackrace": 3,
		"Fouzball": 3,
		"Jenga": 2,
		"PenaltyKick": 2,
		"BallOut": 5,
		"darting": 0,
		"football": 3,
		"cricket": 5,
		"Soap Football": 1,
		"Dodg ball": 5,
		"Tug of war": 0
	},
	{
		"name": "Clayton Jefferson",
		"Chess": 5,
		"Caroms": 3,
		"TT": 3,
		"Badminton": 5,
		"LS": 1,
		"Sackrace": 4,
		"Fouzball": 5,
		"Jenga": 2,
		"PenaltyKick": 3,
		"BallOut": 3,
		"darting": 5,
		"football": 3,
		"cricket": 1,
		"Soap Football": 0,
		"Dodg ball": 1,
		"Tug of war": 2
	},
	{
		"name": "Halla Mcfadden",
		"Chess": 0,
		"Caroms": 5,
		"TT": 5,
		"Badminton": 1,
		"LS": 2,
		"Sackrace": 4,
		"Fouzball": 3,
		"Jenga": 0,
		"PenaltyKick": 1,
		"BallOut": 2,
		"darting": 4,
		"football": 2,
		"cricket": 3,
		"Soap Football": 3,
		"Dodg ball": 3,
		"Tug of war": 4
	},
	{
		"name": "Jakeem Keller",
		"Chess": 2,
		"Caroms": 3,
		"TT": 1,
		"Badminton": 4,
		"LS": 4,
		"Sackrace": 0,
		"Fouzball": 2,
		"Jenga": 1,
		"PenaltyKick": 5,
		"BallOut": 4,
		"darting": 3,
		"football": 5,
		"cricket": 2,
		"Soap Football": 1,
		"Dodg ball": 4,
		"Tug of war": 4
	},
	{
		"name": "Giacomo Winters",
		"Chess": 2,
		"Caroms": 3,
		"TT": 4,
		"Badminton": 2,
		"LS": 1,
		"Sackrace": 5,
		"Fouzball": 4,
		"Jenga": 4,
		"PenaltyKick": 4,
		"BallOut": 4,
		"darting": 2,
		"football": 1,
		"cricket": 3,
		"Soap Football": 3,
		"Dodg ball": 1,
		"Tug of war": 2
	},
	{
		"name": "Driscoll Pruitt",
		"Chess": 0,
		"Caroms": 1,
		"TT": 5,
		"Badminton": 5,
		"LS": 4,
		"Sackrace": 3,
		"Fouzball": 0,
		"Jenga": 1,
		"PenaltyKick": 4,
		"BallOut": 2,
		"darting": 4,
		"football": 5,
		"cricket": 2,
		"Soap Football": 2,
		"Dodg ball": 4,
		"Tug of war": 5
	},
	{
		"name": "Zelenia Cochran",
		"Chess": 1,
		"Caroms": 2,
		"TT": 0,
		"Badminton": 1,
		"LS": 1,
		"Sackrace": 1,
		"Fouzball": 1,
		"Jenga": 4,
		"PenaltyKick": 1,
		"BallOut": 5,
		"darting": 5,
		"football": 0,
		"cricket": 1,
		"Soap Football": 3,
		"Dodg ball": 4,
		"Tug of war": 3
	},
	{
		"name": "Genevieve Scott",
		"Chess": 1,
		"Caroms": 3,
		"TT": 5,
		"Badminton": 3,
		"LS": 4,
		"Sackrace": 3,
		"Fouzball": 4,
		"Jenga": 1,
		"PenaltyKick": 2,
		"BallOut": 2,
		"darting": 1,
		"football": 2,
		"cricket": 3,
		"Soap Football": 0,
		"Dodg ball": 1,
		"Tug of war": 2
	},
	{
		"name": "Malcolm Brooks",
		"Chess": 2,
		"Caroms": 1,
		"TT": 1,
		"Badminton": 1,
		"LS": 1,
		"Sackrace": 1,
		"Fouzball": 5,
		"Jenga": 0,
		"PenaltyKick": 3,
		"BallOut": 1,
		"darting": 4,
		"football": 3,
		"cricket": 5,
		"Soap Football": 5,
		"Dodg ball": 4,
		"Tug of war": 3
	},
	{
		"name": "Odessa Bush",
		"Chess": 0,
		"Caroms": 2,
		"TT": 3,
		"Badminton": 2,
		"LS": 4,
		"Sackrace": 4,
		"Fouzball": 2,
		"Jenga": 4,
		"PenaltyKick": 1,
		"BallOut": 4,
		"darting": 5,
		"football": 0,
		"cricket": 5,
		"Soap Football": 1,
		"Dodg ball": 5,
		"Tug of war": 2
	},
	{
		"name": "Tasha Whitehead",
		"Chess": 1,
		"Caroms": 5,
		"TT": 2,
		"Badminton": 1,
		"LS": 3,
		"Sackrace": 2,
		"Fouzball": 2,
		"Jenga": 5,
		"PenaltyKick": 4,
		"BallOut": 5,
		"darting": 1,
		"football": 1,
		"cricket": 4,
		"Soap Football": 2,
		"Dodg ball": 2,
		"Tug of war": 1
	},
	{
		"name": "Blake Ballard",
		"Chess": 1,
		"Caroms": 5,
		"TT": 2,
		"Badminton": 3,
		"LS": 2,
		"Sackrace": 2,
		"Fouzball": 5,
		"Jenga": 0,
		"PenaltyKick": 2,
		"BallOut": 1,
		"darting": 3,
		"football": 3,
		"cricket": 1,
		"Soap Football": 1,
		"Dodg ball": 4,
		"Tug of war": 4
	},
	{
		"name": "Emmanuel Mcknight",
		"Chess": 3,
		"Caroms": 3,
		"TT": 0,
		"Badminton": 2,
		"LS": 5,
		"Sackrace": 0,
		"Fouzball": 3,
		"Jenga": 1,
		"PenaltyKick": 2,
		"BallOut": 1,
		"darting": 0,
		"football": 2,
		"cricket": 2,
		"Soap Football": 2,
		"Dodg ball": 0,
		"Tug of war": 3
	},
	{
		"name": "Dennis Chase",
		"Chess": 4,
		"Caroms": 2,
		"TT": 4,
		"Badminton": 1,
		"LS": 4,
		"Sackrace": 4,
		"Fouzball": 1,
		"Jenga": 5,
		"PenaltyKick": 1,
		"BallOut": 2,
		"darting": 1,
		"football": 4,
		"cricket": 4,
		"Soap Football": 1,
		"Dodg ball": 4,
		"Tug of war": 2
	},
	{
		"name": "Sara Baxter",
		"Chess": 0,
		"Caroms": 2,
		"TT": 3,
		"Badminton": 3,
		"LS": 0,
		"Sackrace": 4,
		"Fouzball": 3,
		"Jenga": 4,
		"PenaltyKick": 4,
		"BallOut": 4,
		"darting": 1,
		"football": 2,
		"cricket": 4,
		"Soap Football": 3,
		"Dodg ball": 1,
		"Tug of war": 4
	},
	{
		"name": "Hu Mcdaniel",
		"Chess": 2,
		"Caroms": 1,
		"TT": 3,
		"Badminton": 2,
		"LS": 1,
		"Sackrace": 0,
		"Fouzball": 1,
		"Jenga": 1,
		"PenaltyKick": 2,
		"BallOut": 1,
		"darting": 3,
		"football": 0,
		"cricket": 3,
		"Soap Football": 0,
		"Dodg ball": 3,
		"Tug of war": 4
	},
	{
		"name": "Breanna Cox",
		"Chess": 3,
		"Caroms": 2,
		"TT": 0,
		"Badminton": 4,
		"LS": 3,
		"Sackrace": 5,
		"Fouzball": 4,
		"Jenga": 1,
		"PenaltyKick": 2,
		"BallOut": 1,
		"darting": 5,
		"football": 2,
		"cricket": 1,
		"Soap Football": 0,
		"Dodg ball": 1,
		"Tug of war": 4
	},
	{
		"name": "Kylynn Church",
		"Chess": 1,
		"Caroms": 2,
		"TT": 4,
		"Badminton": 3,
		"LS": 3,
		"Sackrace": 1,
		"Fouzball": 2,
		"Jenga": 3,
		"PenaltyKick": 0,
		"BallOut": 2,
		"darting": 5,
		"football": 3,
		"cricket": 5,
		"Soap Football": 4,
		"Dodg ball": 4,
		"Tug of war": 1
	},
	{
		"name": "Tyler Cohen",
		"Chess": 2,
		"Caroms": 4,
		"TT": 2,
		"Badminton": 3,
		"LS": 0,
		"Sackrace": 5,
		"Fouzball": 3,
		"Jenga": 2,
		"PenaltyKick": 3,
		"BallOut": 4,
		"darting": 0,
		"football": 5,
		"cricket": 3,
		"Soap Football": 2,
		"Dodg ball": 5,
		"Tug of war": 2
	},
	{
		"name": "Gray Cox",
		"Chess": 1,
		"Caroms": 2,
		"TT": 1,
		"Badminton": 4,
		"LS": 1,
		"Sackrace": 2,
		"Fouzball": 1,
		"Jenga": 1,
		"PenaltyKick": 4,
		"BallOut": 4,
		"darting": 1,
		"football": 3,
		"cricket": 2,
		"Soap Football": 1,
		"Dodg ball": 3,
		"Tug of war": 1
	},
	{
		"name": "Quemby Eaton",
		"Chess": 1,
		"Caroms": 4,
		"TT": 2,
		"Badminton": 2,
		"LS": 4,
		"Sackrace": 2,
		"Fouzball": 1,
		"Jenga": 0,
		"PenaltyKick": 1,
		"BallOut": 3,
		"darting": 4,
		"football": 3,
		"cricket": 4,
		"Soap Football": 2,
		"Dodg ball": 2,
		"Tug of war": 2
	},
	{
		"name": "Ezra Morris",
		"Chess": 3,
		"Caroms": 0,
		"TT": 3,
		"Badminton": 4,
		"LS": 1,
		"Sackrace": 1,
		"Fouzball": 2,
		"Jenga": 1,
		"PenaltyKick": 5,
		"BallOut": 0,
		"darting": 4,
		"football": 4,
		"cricket": 1,
		"Soap Football": 0,
		"Dodg ball": 0,
		"Tug of war": 1
	},
	{
		"name": "Erasmus Pratt",
		"Chess": 2,
		"Caroms": 4,
		"TT": 4,
		"Badminton": 4,
		"LS": 0,
		"Sackrace": 4,
		"Fouzball": 0,
		"Jenga": 3,
		"PenaltyKick": 1,
		"BallOut": 3,
		"darting": 2,
		"football": 2,
		"cricket": 5,
		"Soap Football": 4,
		"Dodg ball": 3,
		"Tug of war": 2
	},
	{
		"name": "Camden Hatfield",
		"Chess": 2,
		"Caroms": 0,
		"TT": 2,
		"Badminton": 4,
		"LS": 2,
		"Sackrace": 2,
		"Fouzball": 0,
		"Jenga": 2,
		"PenaltyKick": 1,
		"BallOut": 1,
		"darting": 0,
		"football": 4,
		"cricket": 4,
		"Soap Football": 5,
		"Dodg ball": 1,
		"Tug of war": 1
	},
	{
		"name": "Tanisha Massey",
		"Chess": 4,
		"Caroms": 3,
		"TT": 5,
		"Badminton": 1,
		"LS": 5,
		"Sackrace": 3,
		"Fouzball": 1,
		"Jenga": 4,
		"PenaltyKick": 3,
		"BallOut": 5,
		"darting": 1,
		"football": 2,
		"cricket": 1,
		"Soap Football": 1,
		"Dodg ball": 4,
		"Tug of war": 4
	},
	{
		"name": "Xantha Caldwell",
		"Chess": 4,
		"Caroms": 2,
		"TT": 4,
		"Badminton": 3,
		"LS": 4,
		"Sackrace": 4,
		"Fouzball": 4,
		"Jenga": 3,
		"PenaltyKick": 3,
		"BallOut": 4,
		"darting": 3,
		"football": 3,
		"cricket": 2,
		"Soap Football": 3,
		"Dodg ball": 1,
		"Tug of war": 3
	},
	{
		"name": "Heidi Melendez",
		"Chess": 2,
		"Caroms": 3,
		"TT": 4,
		"Badminton": 1,
		"LS": 4,
		"Sackrace": 2,
		"Fouzball": 5,
		"Jenga": 0,
		"PenaltyKick": 3,
		"BallOut": 0,
		"darting": 2,
		"football": 5,
		"cricket": 0,
		"Soap Football": 0,
		"Dodg ball": 4,
		"Tug of war": 2
	},
	{
		"name": "Melodie Kent",
		"Chess": 0,
		"Caroms": 0,
		"TT": 5,
		"Badminton": 4,
		"LS": 4,
		"Sackrace": 1,
		"Fouzball": 0,
		"Jenga": 1,
		"PenaltyKick": 3,
		"BallOut": 2,
		"darting": 1,
		"football": 1,
		"cricket": 2,
		"Soap Football": 2,
		"Dodg ball": 2,
		"Tug of war": 3
	},
	{
		"name": "Karly Flynn",
		"Chess": 3,
		"Caroms": 2,
		"TT": 3,
		"Badminton": 1,
		"LS": 3,
		"Sackrace": 0,
		"Fouzball": 3,
		"Jenga": 4,
		"PenaltyKick": 4,
		"BallOut": 1,
		"darting": 3,
		"football": 1,
		"cricket": 4,
		"Soap Football": 4,
		"Dodg ball": 2,
		"Tug of war": 4
	},
	{
		"name": "Erasmus Rowe",
		"Chess": 5,
		"Caroms": 2,
		"TT": 3,
		"Badminton": 4,
		"LS": 3,
		"Sackrace": 5,
		"Fouzball": 0,
		"Jenga": 1,
		"PenaltyKick": 1,
		"BallOut": 2,
		"darting": 2,
		"football": 4,
		"cricket": 5,
		"Soap Football": 4,
		"Dodg ball": 3,
		"Tug of war": 1
	},
	{
		"name": "Eagan Holman",
		"Chess": 4,
		"Caroms": 0,
		"TT": 2,
		"Badminton": 5,
		"LS": 1,
		"Sackrace": 1,
		"Fouzball": 4,
		"Jenga": 3,
		"PenaltyKick": 2,
		"BallOut": 4,
		"darting": 4,
		"football": 2,
		"cricket": 5,
		"Soap Football": 4,
		"Dodg ball": 2,
		"Tug of war": 1
	},
	{
		"name": "Fredericka Johns",
		"Chess": 3,
		"Caroms": 4,
		"TT": 2,
		"Badminton": 2,
		"LS": 1,
		"Sackrace": 4,
		"Fouzball": 2,
		"Jenga": 1,
		"PenaltyKick": 1,
		"BallOut": 1,
		"darting": 5,
		"football": 2,
		"cricket": 0,
		"Soap Football": 0,
		"Dodg ball": 1,
		"Tug of war": 4
	},
	{
		"name": "Barclay Hill",
		"Chess": 1,
		"Caroms": 0,
		"TT": 0,
		"Badminton": 2,
		"LS": 3,
		"Sackrace": 2,
		"Fouzball": 1,
		"Jenga": 4,
		"PenaltyKick": 3,
		"BallOut": 4,
		"darting": 2,
		"football": 1,
		"cricket": 0,
		"Soap Football": 1,
		"Dodg ball": 3,
		"Tug of war": 3
	},
	{
		"name": "Bradley Molina",
		"Chess": 5,
		"Caroms": 4,
		"TT": 4,
		"Badminton": 1,
		"LS": 4,
		"Sackrace": 0,
		"Fouzball": 4,
		"Jenga": 2,
		"PenaltyKick": 0,
		"BallOut": 3,
		"darting": 4,
		"football": 1,
		"cricket": 1,
		"Soap Football": 4,
		"Dodg ball": 1,
		"Tug of war": 0
	},
	{
		"name": "Amanda Booth",
		"Chess": 4,
		"Caroms": 2,
		"TT": 0,
		"Badminton": 3,
		"LS": 3,
		"Sackrace": 0,
		"Fouzball": 1,
		"Jenga": 3,
		"PenaltyKick": 4,
		"BallOut": 0,
		"darting": 3,
		"football": 0,
		"cricket": 4,
		"Soap Football": 1,
		"Dodg ball": 3,
		"Tug of war": 0
	},
	{
		"name": "Arthur Booth",
		"Chess": 2,
		"Caroms": 4,
		"TT": 3,
		"Badminton": 1,
		"LS": 4,
		"Sackrace": 2,
		"Fouzball": 1,
		"Jenga": 4,
		"PenaltyKick": 4,
		"BallOut": 0,
		"darting": 4,
		"football": 1,
		"cricket": 2,
		"Soap Football": 0,
		"Dodg ball": 3,
		"Tug of war": 3
	},
	{
		"name": "Lucas Pennington",
		"Chess": 2,
		"Caroms": 3,
		"TT": 1,
		"Badminton": 1,
		"LS": 1,
		"Sackrace": 4,
		"Fouzball": 5,
		"Jenga": 1,
		"PenaltyKick": 5,
		"BallOut": 3,
		"darting": 2,
		"football": 2,
		"cricket": 4,
		"Soap Football": 4,
		"Dodg ball": 2,
		"Tug of war": 4
	},
	{
		"name": "Philip Clay",
		"Chess": 4,
		"Caroms": 2,
		"TT": 4,
		"Badminton": 0,
		"LS": 2,
		"Sackrace": 2,
		"Fouzball": 3,
		"Jenga": 3,
		"PenaltyKick": 3,
		"BallOut": 3,
		"darting": 2,
		"football": 1,
		"cricket": 0,
		"Soap Football": 5,
		"Dodg ball": 3,
		"Tug of war": 5
	}
];
  
  const numTeams = 4;
  const teamNames = ['A','B', 'C','D']
  const groupEvents = ["Tug of war", "Dodge ball", "Soap Football", "cricket", "football", "darting", "BallOut", "Sackrace"];
  const individualItems = ["Chess", "Caroms", "TT", "Badminton", "LS", "Fouzball", "Jenga", "PenaltyKick"];;
  const resultTeams = createTeams(playersdetails,individualItems,groupEvents, numTeams, teamNames);
  
  console.log(resultTeams);